FROM python:3.6.4

# Cài đặt các gói bắt buộc cho môi trường
RUN apt-get update -y\
    && apt-get install -y --no-install-recommends netcat\
    && apt-get clean

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add requirements
COPY ./requirements.txt /usr/src/app/requirements.txt

# install requirements
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Thêm tệp entrypoint.sh
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh

# add app
COPY . /usr/src/app

# run server
CMD ["./entrypoint-prod.sh"]
